# fly.toml app configuration file generated for eventmap on 2023-05-05T14:47:50+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "eventmap"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[[mounts]]
  source = "eventmap_data"
  destination = "/data"
  processes = ["app"]

[env]
  COOKIE_NAME = "EVENTMAP_SID"
  DATABASE_URL = "/data/eventmap.db?_journal_mode=WAL"
#  FACEBOOK_CLIENT_ID=""
#  FACEBOOK_CLIENT_SECRET=""
  FACEBOOK_REDIRECT_URI = "https://eventmap.app/login/oauth2/code/facebook"
  FACEBOOK_USER_INFO_URL = "https://graph.facebook.com/v10.0/me?fields=id,name,picture{url},email"
#  GITHUB_CLIENT_ID=""
#  GITHUB_CLIENT_SECRET=""
  GITHUB_REDIRECT_URI = "https://eventmap.app/login/oauth2/code/github"
  GITHUB_USER_INFO_URL = "https://api.github.com/user"
#  GOOGLE_MAPS_API_KEY=""
#  GOOGLE_CLIENT_ID=""
#  GOOGLE_CLIENT_SECRET=""
  GOOGLE_REDIRECT_URI = "https://eventmap.app/login/oauth2/code/google"
  GOOGLE_USER_INFO_URL = "https://www.googleapis.com/oauth2/v3/userinfo"
#  LINE_CLIENT_ID=""
#  LINE_CLIENT_SECRET=""
  LINE_REDIRECT_URI = "https://eventmap.app/login/oauth2/code/line"
  LINE_USER_INFO_URL = "https://api.line.me/v2/profile"
  PORT = "8080"
