version: '3'

vars:
  EXE: eventmapd
  USER: ec2-user
  HOST: eventmap.app
  PORT: 22

tasks:
  default:
    deps: [grpc, assets, build]

  tools:
    cmds:
      - echo install tools
      - go install github.com/bufbuild/buf/cmd/buf@latest
      - go install github.com/bufbuild/connect-go/cmd/protoc-gen-connect-go@latest
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

  grpc:
    cmds:
      - buf generate

  build:
    cmds:
      - go build -trimpath -ldflags="-s -w" ./cmd/eventmapd

  build-backupdb:
    cmds:
      - go build -trimpath -ldflags="-s -w" ./cmd/backupdb

  assets:
    dir: frontend
    cmds:
      - npm install
      - quasar build
    method: timestamp
    sources:
      - ./*.js
      - ./*.json
      - src/**/*
      - gen/**/*
    generates:
      - dist/**/*

  deploy-cross-compile:
    deps: [build-freebsd]
    cmds:
      - echo stop service
      - ssh -t -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo service {{.EXE}} stop"
      - echo uploading
      - scp -P {{.PORT}} {{.EXE}} {{.USER}}@{{.HOST}}:.
      - echo start service
      - ssh -t -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo service {{.EXE}} start"

  deploy:
    deps: [grpc, assets]
    cmds:
      - echo packing
      - git archive main -o main.zip
      - C:\\Program\ Files\\7-zip\\7z.exe a main.zip gen
      - C:\\Program\ Files\\7-zip\\7z.exe a main.zip frontend\\dist\\spa
      - echo uploading
      - scp -P {{.PORT}} main.zip {{.USER}}@{{.HOST}}:.
      - cmd /c del main.zip
      - echo building
      - ssh -t -p {{.PORT}} {{.USER}}@{{.HOST}} "mkdir main; unzip -q -d main main.zip; cd main; ../go/bin/task build"
      - echo stop service
      - cmd: ssh -t -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo service {{.EXE}} stop"
        ignore_error: true
      - ssh -t -p {{.PORT}} {{.USER}}@{{.HOST}} "cp main/{{.EXE}} .; rm -rf main; rm -f main.zip"
      - echo start service
      - ssh -t -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo service {{.EXE}} start"

  deploy-backupdb:
    cmds:
      - echo packing
      - git archive main -o main.zip
      - echo uploading
      - scp -P {{.PORT}} main.zip {{.USER}}@{{.HOST}}:.
      - cmd /c del main.zip
      - echo building
      - ssh -t -p {{.PORT}} {{.USER}}@{{.HOST}} "mkdir main; unzip -q -d main main.zip; cd main; ../go/bin/task build-backupdb"
      - ssh -t -p {{.PORT}} {{.USER}}@{{.HOST}} "cp main/backupdb .; rm -rf main; rm -f main.zip"

  gosec:
    dir: echo
    cmds:
      - go install github.com/securego/gosec/cmd/gosec@latest
      - gosec --quiet ./...
