version: '3'

vars:
  EXE: eventmap
  USER: ec2-user
  HOST: eventmap.app
  PORT: 22

tasks:
  default:
    deps: [build-windows]

  tools:
    cmds:
      - echo install tools
      - go install github.com/bufbuild/buf/cmd/buf@latest
      - go install github.com/bufbuild/connect-go/cmd/protoc-gen-connect-go@latest
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

  grpc:
    deps: [tools]
    cmds:
      - buf generate

  build-windows:
    deps: [assets]
    cmds:
      - go build -trimpath -ldflags="-s -w" .

  build-freebsd:
    deps: [assets]
    env:
      GOARCH: amd64
      GOOS: freebsd
    cmds:
      - go build -trimpath -ldflags="-s -w" .

  build-linux:
    deps: [assets]
    env:
      GOARCH: amd64
      GOOS: linux
    cmds:
      - go build -trimpath -ldflags="-s -w" .

  assets:
    deps: [grpc]
    dir: frontend
    cmds:
      - npm install
      - quasar build
    method: timestamp
    sources:
      - ./*.js
      - ./*.json
      - src/**/*
    generates:
      - dist/**/*

  deploy-cross-compile:
    deps: [build-freebsd]
    cmds:
      - echo stop service
      - ssh -t -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo service {{.EXE}} stop"
      - echo uploading
      - scp -P {{.PORT}} {{.EXE}} {{.USER}}@{{.HOST}}:.
      - echo start service
      - ssh -t -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo service {{.EXE}} start"

  deploy:
    deps: [assets]
    cmds:
      - echo packing
      - git archive main -o main.zip
      - C:\\Program\ Files\\7-zip\\7z.exe a main.zip gen
      - C:\\Program\ Files\\7-zip\\7z.exe a main.zip frontend\\dist\\spa
      - echo uploading
      - scp -P {{.PORT}} main.zip {{.USER}}@{{.HOST}}:.
      - cmd /c del main.zip
      - echo building
      - ssh -t -p {{.PORT}} {{.USER}}@{{.HOST}} "mkdir main; unzip -q -d main main.zip; cd main; go build -trimpath -ldflags=\"-s -w\" ."
      - echo stop service
      - cmd: ssh -t -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo service {{.EXE}} stop"
        ignore_error: true
      - ssh -t -p {{.PORT}} {{.USER}}@{{.HOST}} "cp main/{{.EXE}} .; rm -rf main; rm -f main.zip"
      - echo start service
      - ssh -t -p {{.PORT}} {{.USER}}@{{.HOST}} "sudo service {{.EXE}} start"

  gosec:
    dir: echo
    cmds:
      - go install github.com/securego/gosec/cmd/gosec@latest
      - gosec --quiet ./...

  swag:
    dir: echo
    cmds:
      - go install github.com/swaggo/swag/cmd/swag@latest
      - swag init
